// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type BillingFreq string

const (
	BillingFreqMonthly BillingFreq = "monthly"
	BillingFreqYearly  BillingFreq = "yearly"
)

func (e *BillingFreq) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BillingFreq(s)
	case string:
		*e = BillingFreq(s)
	default:
		return fmt.Errorf("unsupported scan type for BillingFreq: %T", src)
	}
	return nil
}

type NullBillingFreq struct {
	BillingFreq BillingFreq `json:"billing_freq"`
	Valid       bool        `json:"valid"` // Valid is true if BillingFreq is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBillingFreq) Scan(value interface{}) error {
	if value == nil {
		ns.BillingFreq, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BillingFreq.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBillingFreq) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BillingFreq), nil
}

type EscrowStatus string

const (
	EscrowStatusHeld     EscrowStatus = "held"
	EscrowStatusReleased EscrowStatus = "released"
	EscrowStatusDisputed EscrowStatus = "disputed"
	EscrowStatusRefunded EscrowStatus = "refunded"
)

func (e *EscrowStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EscrowStatus(s)
	case string:
		*e = EscrowStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EscrowStatus: %T", src)
	}
	return nil
}

type NullEscrowStatus struct {
	EscrowStatus EscrowStatus `json:"escrow_status"`
	Valid        bool         `json:"valid"` // Valid is true if EscrowStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEscrowStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EscrowStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EscrowStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEscrowStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EscrowStatus), nil
}

type PropertyType string

const (
	PropertyTypeLongTerm PropertyType = "long_term"
	PropertyTypeSeasonal PropertyType = "seasonal"
)

func (e *PropertyType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PropertyType(s)
	case string:
		*e = PropertyType(s)
	default:
		return fmt.Errorf("unsupported scan type for PropertyType: %T", src)
	}
	return nil
}

type NullPropertyType struct {
	PropertyType PropertyType `json:"property_type"`
	Valid        bool         `json:"valid"` // Valid is true if PropertyType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPropertyType) Scan(value interface{}) error {
	if value == nil {
		ns.PropertyType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PropertyType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPropertyType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PropertyType), nil
}

type SolvencyStatus string

const (
	SolvencyStatusPending          SolvencyStatus = "pending"
	SolvencyStatusApproved         SolvencyStatus = "approved"
	SolvencyStatusRejected         SolvencyStatus = "rejected"
	SolvencyStatusInsufficientDocs SolvencyStatus = "insufficient_docs"
)

func (e *SolvencyStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SolvencyStatus(s)
	case string:
		*e = SolvencyStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SolvencyStatus: %T", src)
	}
	return nil
}

type NullSolvencyStatus struct {
	SolvencyStatus SolvencyStatus `json:"solvency_status"`
	Valid          bool           `json:"valid"` // Valid is true if SolvencyStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSolvencyStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SolvencyStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SolvencyStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSolvencyStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SolvencyStatus), nil
}

type SubPlan string

const (
	SubPlanDiscovery SubPlan = "discovery"
	SubPlanSerenity  SubPlan = "serenity"
	SubPlanPremium   SubPlan = "premium"
)

func (e *SubPlan) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubPlan(s)
	case string:
		*e = SubPlan(s)
	default:
		return fmt.Errorf("unsupported scan type for SubPlan: %T", src)
	}
	return nil
}

type NullSubPlan struct {
	SubPlan SubPlan `json:"sub_plan"`
	Valid   bool    `json:"valid"` // Valid is true if SubPlan is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubPlan) Scan(value interface{}) error {
	if value == nil {
		ns.SubPlan, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubPlan.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubPlan) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubPlan), nil
}

type UserRole string

const (
	UserRoleAdmin UserRole = "admin"
	UserRoleUser  UserRole = "user"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type CreditTransaction struct {
	ID              int32            `json:"id"`
	UserID          pgtype.Int4      `json:"user_id"`
	Amount          int32            `json:"amount"`
	TransactionType string           `json:"transaction_type"`
	Description     pgtype.Text      `json:"description"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

type Lease struct {
	ID                  int32            `json:"id"`
	PropertyID          pgtype.Int4      `json:"property_id"`
	TenantID            pgtype.Int4      `json:"tenant_id"`
	StartDate           pgtype.Date      `json:"start_date"`
	EndDate             pgtype.Date      `json:"end_date"`
	RentAmount          pgtype.Numeric   `json:"rent_amount"`
	DepositAmount       pgtype.Numeric   `json:"deposit_amount"`
	LeaseStatus         pgtype.Text      `json:"lease_status"`
	ContractUrl         pgtype.Text      `json:"contract_url"`
	EscrowDepositStatus NullEscrowStatus `json:"escrow_deposit_status"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
}

type LeaseInvitation struct {
	ID          int32            `json:"id"`
	PropertyID  int32            `json:"property_id"`
	OwnerID     int32            `json:"owner_id"`
	TenantEmail string           `json:"tenant_email"`
	Token       string           `json:"token"`
	Status      pgtype.Text      `json:"status"`
	ExpiresAt   pgtype.Timestamp `json:"expires_at"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Property struct {
	ID             int32            `json:"id"`
	OwnerID        pgtype.Int4      `json:"owner_id"`
	Address        string           `json:"address"`
	RentalType     PropertyType     `json:"rental_type"`
	Details        []byte           `json:"details"`
	RentAmount     pgtype.Numeric   `json:"rent_amount"`
	DepositAmount  pgtype.Numeric   `json:"deposit_amount"`
	VacancyCredits int32            `json:"vacancy_credits"`
	IsActive       pgtype.Bool      `json:"is_active"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type RentPayment struct {
	ID                int32            `json:"id"`
	LeaseID           pgtype.Int4      `json:"lease_id"`
	Amount            pgtype.Numeric   `json:"amount"`
	DueDate           pgtype.Date      `json:"due_date"`
	PaymentDate       pgtype.Timestamp `json:"payment_date"`
	Status            pgtype.Text      `json:"status"`
	ReceiptUrl        pgtype.Text      `json:"receipt_url"`
	IsSepaDirectDebit pgtype.Bool      `json:"is_sepa_direct_debit"`
}

type SeasonalBooking struct {
	ID                 int32            `json:"id"`
	PropertyID         pgtype.Int4      `json:"property_id"`
	TenantID           pgtype.Int4      `json:"tenant_id"`
	CheckInDate        pgtype.Date      `json:"check_in_date"`
	CheckOutDate       pgtype.Date      `json:"check_out_date"`
	TotalAmount        pgtype.Numeric   `json:"total_amount"`
	PlatformFeePercent pgtype.Numeric   `json:"platform_fee_percent"`
	CommissionAmount   pgtype.Numeric   `json:"commission_amount"`
	PayoutAmount       pgtype.Numeric   `json:"payout_amount"`
	EscrowStatus       NullEscrowStatus `json:"escrow_status"`
	BookingStatus      pgtype.Text      `json:"booking_status"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
}

type SolvencyCheck struct {
	ID               int32              `json:"id"`
	InitiatorOwnerID pgtype.Int4        `json:"initiator_owner_id"`
	CandidateEmail   string             `json:"candidate_email"`
	PropertyID       pgtype.Int4        `json:"property_id"`
	Status           NullSolvencyStatus `json:"status"`
	ScoreResult      pgtype.Int4        `json:"score_result"`
	ReportUrl        pgtype.Text        `json:"report_url"`
	DocumentsJson    []byte             `json:"documents_json"`
	CreatedAt        pgtype.Timestamp   `json:"created_at"`
}

type Subscription struct {
	ID                 int32            `json:"id"`
	UserID             pgtype.Int4      `json:"user_id"`
	PlanType           SubPlan          `json:"plan_type"`
	Frequency          NullBillingFreq  `json:"frequency"`
	Status             pgtype.Text      `json:"status"`
	StartDate          pgtype.Date      `json:"start_date"`
	EndDate            pgtype.Date      `json:"end_date"`
	MaxPropertiesLimit pgtype.Int4      `json:"max_properties_limit"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
}

type Transaction struct {
	ID                    int32            `json:"id"`
	UserID                pgtype.Int4      `json:"user_id"`
	RelatedEntityType     pgtype.Text      `json:"related_entity_type"`
	RelatedEntityID       pgtype.Int4      `json:"related_entity_id"`
	Amount                pgtype.Numeric   `json:"amount"`
	Currency              pgtype.Text      `json:"currency"`
	Direction             pgtype.Text      `json:"direction"`
	StripePaymentIntentID pgtype.Text      `json:"stripe_payment_intent_id"`
	Status                pgtype.Text      `json:"status"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID               int32            `json:"id"`
	Email            string           `json:"email"`
	PasswordHash     string           `json:"password_hash"`
	FirstName        pgtype.Text      `json:"first_name"`
	LastName         pgtype.Text      `json:"last_name"`
	PhoneNumber      pgtype.Text      `json:"phone_number"`
	IsVerified       pgtype.Bool      `json:"is_verified"`
	StripeCustomerID pgtype.Text      `json:"stripe_customer_id"`
	LastContextUsed  pgtype.Text      `json:"last_context_used"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
}

type ViewUserCreditBalance struct {
	UserID         pgtype.Int4 `json:"user_id"`
	CurrentBalance int64       `json:"current_balance"`
}
