// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCreditTransaction = `-- name: CreateCreditTransaction :one
INSERT INTO credit_transactions (
    user_id, amount, transaction_type, description
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, user_id, amount, transaction_type, description, created_at
`

type CreateCreditTransactionParams struct {
	UserID          pgtype.Int4 `json:"user_id"`
	Amount          int32       `json:"amount"`
	TransactionType string      `json:"transaction_type"`
	Description     pgtype.Text `json:"description"`
}

func (q *Queries) CreateCreditTransaction(ctx context.Context, arg CreateCreditTransactionParams) (CreditTransaction, error) {
	row := q.db.QueryRow(ctx, createCreditTransaction,
		arg.UserID,
		arg.Amount,
		arg.TransactionType,
		arg.Description,
	)
	var i CreditTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.TransactionType,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
    user_id, plan_type, frequency, start_date, end_date, max_properties_limit
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, plan_type, frequency, status, start_date, end_date, max_properties_limit, created_at
`

type CreateSubscriptionParams struct {
	UserID             pgtype.Int4     `json:"user_id"`
	PlanType           SubPlan         `json:"plan_type"`
	Frequency          NullBillingFreq `json:"frequency"`
	StartDate          pgtype.Date     `json:"start_date"`
	EndDate            pgtype.Date     `json:"end_date"`
	MaxPropertiesLimit pgtype.Int4     `json:"max_properties_limit"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.UserID,
		arg.PlanType,
		arg.Frequency,
		arg.StartDate,
		arg.EndDate,
		arg.MaxPropertiesLimit,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanType,
		&i.Frequency,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.MaxPropertiesLimit,
		&i.CreatedAt,
	)
	return i, err
}

const getUserCreditBalance = `-- name: GetUserCreditBalance :one
SELECT current_balance::int FROM view_user_credit_balance
WHERE user_id = $1
`

func (q *Queries) GetUserCreditBalance(ctx context.Context, userID pgtype.Int4) (int32, error) {
	row := q.db.QueryRow(ctx, getUserCreditBalance, userID)
	var current_balance int32
	err := row.Scan(&current_balance)
	return current_balance, err
}

const getUserSubscription = `-- name: GetUserSubscription :one
SELECT id, user_id, plan_type, frequency, status, start_date, end_date, max_properties_limit, created_at FROM subscriptions
WHERE user_id = $1 AND status = 'active'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetUserSubscription(ctx context.Context, userID pgtype.Int4) (Subscription, error) {
	row := q.db.QueryRow(ctx, getUserSubscription, userID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanType,
		&i.Frequency,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.MaxPropertiesLimit,
		&i.CreatedAt,
	)
	return i, err
}
