// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCreditTransaction(ctx context.Context, arg CreateCreditTransactionParams) (CreditTransaction, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	GetUserCreditBalance(ctx context.Context, userID pgtype.Int4) (int32, error)
	GetUserSubscription(ctx context.Context, userID pgtype.Int4) (Subscription, error)
}

var _ Querier = (*Queries)(nil)
