// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CancelSolvencyCheck(ctx context.Context, id int32) error
	CleanupProvisionalUsers(ctx context.Context) error
	CountBookingsByTenant(ctx context.Context, tenantID pgtype.Int4) (int64, error)
	CountLeasesByTenant(ctx context.Context, tenantID pgtype.Int4) (int64, error)
	CountPropertiesByOwner(ctx context.Context, ownerID pgtype.Int4) (int64, error)
	CountPropertiesByOwnerAndType(ctx context.Context, arg CountPropertiesByOwnerAndTypeParams) (int64, error)
	CreateCreditTransaction(ctx context.Context, arg CreateCreditTransactionParams) (CreditTransaction, error)
	CreateDraftLease(ctx context.Context, arg CreateDraftLeaseParams) (Lease, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (LeaseInvitation, error)
	CreateInvitationWithLease(ctx context.Context, arg CreateInvitationWithLeaseParams) (LeaseInvitation, error)
	CreateLease(ctx context.Context, arg CreateLeaseParams) (Lease, error)
	CreateProperty(ctx context.Context, arg CreatePropertyParams) (Property, error)
	CreateSolvencyCheck(ctx context.Context, arg CreateSolvencyCheckParams) (SolvencyCheck, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DecreasePropertyCredits(ctx context.Context, id int32) error
	GetInvitationByEmailAndProperty(ctx context.Context, arg GetInvitationByEmailAndPropertyParams) (LeaseInvitation, error)
	GetInvitationByLeaseID(ctx context.Context, leaseID pgtype.Int4) (LeaseInvitation, error)
	GetInvitationByToken(ctx context.Context, token string) (LeaseInvitation, error)
	GetLease(ctx context.Context, id int32) (Lease, error)
	GetLeaseByPropertyAndStatus(ctx context.Context, arg GetLeaseByPropertyAndStatusParams) (Lease, error)
	GetProperty(ctx context.Context, id int32) (Property, error)
	GetPropertyForUpdate(ctx context.Context, id int32) (Property, error)
	GetSolvencyCheckByID(ctx context.Context, id int32) (SolvencyCheck, error)
	GetSolvencyCheckByToken(ctx context.Context, token pgtype.Text) (GetSolvencyCheckByTokenRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id int32) (User, error)
	GetUserCreditBalance(ctx context.Context, userID pgtype.Int4) (int32, error)
	GetUserCreditBalanceForUpdate(ctx context.Context, userID pgtype.Int4) (int32, error)
	GetUserForUpdate(ctx context.Context, id int32) (User, error)
	GetUserSubscription(ctx context.Context, userID pgtype.Int4) (Subscription, error)
	HasReceivedInitialBonus(ctx context.Context, userID pgtype.Int4) (bool, error)
	IncreasePropertyCredits(ctx context.Context, id int32) error
	ListLeasesByTenant(ctx context.Context, tenantID pgtype.Int4) ([]ListLeasesByTenantRow, error)
	ListPropertiesByOwner(ctx context.Context, ownerID pgtype.Int4) ([]Property, error)
	ListSolvencyChecksByOwner(ctx context.Context, initiatorOwnerID pgtype.Int4) ([]ListSolvencyChecksByOwnerRow, error)
	ListSolvencyChecksByProperty(ctx context.Context, propertyID pgtype.Int4) ([]ListSolvencyChecksByPropertyRow, error)
	SoftDeleteProperty(ctx context.Context, arg SoftDeletePropertyParams) (int32, error)
	UpdateInvitationStatus(ctx context.Context, arg UpdateInvitationStatusParams) error
	UpdateLastContext(ctx context.Context, arg UpdateLastContextParams) error
	UpdateLeaseContractURL(ctx context.Context, arg UpdateLeaseContractURLParams) error
	UpdateLeaseTenant(ctx context.Context, arg UpdateLeaseTenantParams) error
	UpdateProperty(ctx context.Context, arg UpdatePropertyParams) (Property, error)
	UpdateSolvencyCheckResult(ctx context.Context, arg UpdateSolvencyCheckResultParams) error
	UpdateSubscriptionLimit(ctx context.Context, arg UpdateSubscriptionLimitParams) error
	UpdateUserPromotion(ctx context.Context, arg UpdateUserPromotionParams) error
}

var _ Querier = (*Queries)(nil)
