package app

import (
	"net/http"
	"time"

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/spf13/viper"
	"github.com/ulule/limiter/v3"
	mgin "github.com/ulule/limiter/v3/drivers/middleware/gin"
	"github.com/ulule/limiter/v3/drivers/store/memory"
	"go.uber.org/zap"

	"seculoc-back/internal/adapter/http/handler"
	"seculoc-back/internal/adapter/http/middleware"
	"seculoc-back/internal/adapter/storage/local"
	"seculoc-back/internal/adapter/storage/postgres"
	"seculoc-back/internal/core/service"
	"seculoc-back/internal/platform/email"

	docs "seculoc-back/docs" // Swagger docs generated by swaggo

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// NewServer wires up the application and returns the Gin engine.
func NewServer(pool *pgxpool.Pool, log *zap.Logger) *gin.Engine {
	// 1. Persistence Layer (TxManager)
	txManager := postgres.NewTxManager(pool)

	// 2. Service Layer
	emailSender := email.NewMockEmailSender(log)
	frontendURL := viper.GetString("FRONTEND_URL")
	if frontendURL == "" {
		frontendURL = "http://localhost:5173"
	}

	fileStore, err := local.NewFileStore()
	if err != nil {
		log.Fatal("failed to initialize file store", zap.Error(err))
	}
	leaseService := service.NewLeaseService(txManager, log, fileStore)

	userService := service.NewUserService(txManager, log, emailSender, frontendURL, leaseService)
	propService := service.NewPropertyService(txManager, log)
	subService := service.NewSubscriptionService(txManager, log)
	solvService := service.NewSolvencyService(txManager, emailSender, log)

	// 3. Adapters (Handlers)
	userHandler := handler.NewUserHandler(userService)
	propHandler := handler.NewPropertyHandler(propService)
	subHandler := handler.NewSubscriptionHandler(subService, userService)
	solvHandler := handler.NewSolvencyHandler(solvService)
	invHandler := handler.NewInvitationHandler(userService)
	leaseHandler := handler.NewLeaseHandler(leaseService)

	// 4. HTTP Router (Gin)
	if viper.GetString("GIN_MODE") == "release" {
		gin.SetMode(gin.ReleaseMode)
	}
	r := gin.New()

	// Middleware
	r.Use(middleware.RequestLogger())
	r.Use(middleware.SecurityHeadersMiddleware())
	r.Use(gin.Recovery())

	configureCORS(r)
	configureRateLimit(r)

	// Public Routes
	api := r.Group("/api/v1")
	{
		api.GET("/invitations/:token", invHandler.GetInvitation)
		api.GET("/solvency/public/check/:token", solvHandler.GetCheckByToken)
		api.POST("/solvency/public/check/:token/callback", solvHandler.ProcessCallback)

		authGroup := api.Group("/auth")
		{
			authGroup.POST("/register", userHandler.Register)
			authGroup.POST("/login", userHandler.Login)
		}

		// Protected Routes
		protected := api.Group("")
		protected.Use(middleware.AuthMiddleware())
		{
			protected.POST("/auth/switch-context", userHandler.SwitchContext)
			// Properties
			protected.POST("/properties", propHandler.Create)
			protected.GET("/properties", propHandler.List)
			protected.PUT("/properties/:id", propHandler.Update)
			protected.DELETE("/properties/:id", propHandler.Delete)

			// Leases
			protected.GET("/leases", leaseHandler.List)
			protected.POST("/leases/draft", leaseHandler.CreateDraft)
			protected.GET("/leases/:id/download", leaseHandler.Download)
			protected.GET("/leases/:id/preview", leaseHandler.Preview)

			// Subscriptions
			protected.POST("/subscriptions", subHandler.Subscribe)
			protected.POST("/subscriptions/upgrade", subHandler.IncreaseLimit)

			// Solvency
			protected.POST("/solvency/check", solvHandler.CreateCheck)
			protected.POST("/solvency/check/:id/cancel", solvHandler.CancelCheck)
			protected.GET("/solvency/checks", solvHandler.ListChecks)
			protected.POST("/solvency/credits", solvHandler.BuyCredits)

			// Invitations
			protected.POST("/invitations", invHandler.InviteTenant)
			protected.POST("/invitations/accept", invHandler.AcceptInvitation)
		}
	}

	// Health Check
	r.GET("/health", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{"status": "ok"})
	})

	// Swagger UI
	docs.SwaggerInfo.BasePath = "/api/v1"
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	return r
}

func configureCORS(r *gin.Engine) {
	frontendURL := viper.GetString("FRONTEND_URL")
	if frontendURL == "" {
		frontendURL = "http://localhost:5173"
	}
	corsConfig := cors.DefaultConfig()
	corsConfig.AllowOrigins = []string{frontendURL}
	corsConfig.AllowMethods = []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"}
	corsConfig.AllowHeaders = []string{"Origin", "Content-Type", "Authorization"}
	corsConfig.ExposeHeaders = []string{"Content-Length", "Content-Disposition"}
	corsConfig.AllowCredentials = true
	r.Use(cors.New(corsConfig))
}

func configureRateLimit(r *gin.Engine) {
	// Skip in Test mode to avoid blocking E2E tests
	if viper.GetString("GIN_MODE") == "test" {
		return
	}

	// Define a rate: 20 reqs/second
	rate := limiter.Rate{
		Period: 1 * time.Second,
		Limit:  20,
	}

	// Store
	store := memory.NewStore()

	// Instance
	instance := limiter.New(store, rate)

	// Middleware
	r.Use(mgin.NewMiddleware(instance))
}
